sudo: false
language: go
go_import_path: github.com/prometheus/alertmanager

services:
- docker

go:
- 1.10.x

script:
# test front-end
- make clean
- cd ui/app/ && make && cd ../..
- make assets
- git diff --exit-code
# test back-end
- make
